# Practica 2
### Carles Westendorf Vidal, Javier Cisneros Serra, Gabriel Morales Cardona

```{r, echo=FALSE, message=FALSE}
library(tidyverse)
```



Correo Daniel Covacho:
dcovacho@gmail.com

```{r}
raw_data = read.csv("Salut_Vocal_anonimizada.csv", header=TRUE, encoding = 'UTF-8', stringsAsFactors=FALSE, sep=';')
```

```{r}
str(raw_data)
nomsColumnes= c("ID", "Import_veu", "Sexe", "Lloc_Feina", "cos_docent", "edat", "practica_esport", "import_esport", "qualitat_son", "consum_cafe", "consum_tabac", "consum_alcohol", "consum_gas", "dieta_equil", "malalties", "patologia", "diagnosticat", "sintomes_darrerMes", "operat_cordes", "inici_alteracio", "baixa_laboral", "detalls_baixa", "problemes2223", "formacio_saludVocal", "consum_medicaments", "rutina_higiene", "activitats_oci", 1:10)

data <- as_tibble(raw_data)
colnames(data) <- nomsColumnes
data <- data %>% mutate(puntTotal = , case_when())
data <- data %>% mutate(puntTotal = 1+2+3+4+5+6+7+8+9+10)
```



Mutate, crear var total y sumar resultados (por columnas) (mapping 0 to 4 each answer)